# Generated by Django 5.2.4 on 2025-08-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('event_id', models.BigAutoField(help_text='事件唯一ID', primary_key=True, serialize=False)),
                ('stock_code', models.CharField(help_text="股票代码, 格式如 'sh.600000'", max_length=10)),
                ('ex_dividend_date', models.DateField(db_index=True, help_text='除权除息日 (策略判断的基准日期)')),
                ('record_date', models.DateField(blank=True, help_text='股权登记日', null=True)),
                ('notice_date', models.DateField(blank=True, help_text='公告日期', null=True)),
                ('event_type', models.CharField(choices=[('dividend', '分红'), ('bonus', '送股'), ('transfer', '转股'), ('rights', '配股'), ('split', '拆股/并股')], help_text='事件类型。枚举: dividend(分红), bonus(送股), transfer(转股),rights(配股), split(拆股/并股)', max_length=20)),
                ('dividend_per_share', models.DecimalField(blank=True, decimal_places=4, help_text='每股派息(税前, 元，分红专用)', max_digits=10, null=True)),
                ('shares_before', models.DecimalField(blank=True, decimal_places=4, help_text='基准股数 (如“10送5”，此值为10，送股/转股/拆股/并股专用)', max_digits=10, null=True)),
                ('shares_after', models.DecimalField(blank=True, decimal_places=4, help_text='变动股数 (如“10送5”，此值为15，送股/转股/拆股/并股专用)', max_digits=10, null=True)),
                ('rights_issue_price', models.DecimalField(blank=True, decimal_places=2, help_text='配股价格，配股专用', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
            ],
            options={
                'verbose_name': '股权事件',
                'verbose_name_plural': '股权事件',
                'db_table': 'tb_corporate_actions',
                'ordering': ['-ex_dividend_date', 'stock_code'],
            },
        ),
    ]
