# Generated by Django 5.2.4 on 2025-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_corporateaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateaction',
            name='ex_dividend_date',
            field=models.DateField(db_index=True, help_text='除权除息日 (策略判断的基准日期)，对于配股来说，实际为股权登记日而非除权日'),
        ),
    ]
