# Generated by Django 5.2.4 on 2025-08-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_corporateaction_ex_dividend_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='related_buy_trade',
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='status',
            field=models.CharField(choices=[('filled', '已成交'), ('failed', '失败'), ('cancelled', '已撤销'), ('pending', '待执行')], help_text='订单状态。枚举: filled(已成交), failed(失败), cancelled(已撤销),pending(待执行)', max_length=20),
        ),
    ]
