# Generated by Django 5.2.4 on 2025-08-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_position_related_buy_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='external_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='外部交易系统的订单ID，如券商的委托编号', max_length=50, null=True),
        ),
    ]
