# Generated by Django 5.2.4 on 2025-08-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_tradelog_external_order_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyquotes',
            index=models.Index(fields=['trade_date'], name='dailyquotes_tradedate_idx'),
        ),
    ]
