# Generated by Django 5.2.4 on 2025-08-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_dailyquotes_dailyquotes_tradedate_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateaction',
            name='stock_code',
            field=models.CharField(help_text="股票代码, 格式如 'sh.600000'", max_length=50),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='stock_code',
            field=models.CharField(help_text="股票代码, 格式如 'sh.600000'", max_length=50, primary_key=True, serialize=False),
        ),
    ]
