# Generated by Django 5.2.4 on 2025-08-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_corporateaction_stock_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtest_run_id', models.CharField(db_index=True, help_text="回测运行的唯一标识符, 如 'backtest_20231027_153000'", max_length=50)),
                ('trade_date', models.DateField(help_text='交易日期')),
                ('total_assets', models.DecimalField(decimal_places=4, help_text='当日日终总资产 (现金 + 持仓市值)', max_digits=20)),
                ('cash', models.DecimalField(decimal_places=4, help_text='当日日终现金余额', max_digits=20)),
                ('holdings_value', models.DecimalField(decimal_places=4, help_text='当日日终持仓市值', max_digits=20)),
                ('market_m_value', models.DecimalField(blank=True, decimal_places=10, help_text='当日的市场状态M(t)值', max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
            ],
            options={
                'verbose_name': '回测每日日志',
                'verbose_name_plural': '回测每日日志',
                'db_table': 'tb_trade_manager_backtest_daily_log',
                'ordering': ['backtest_run_id', 'trade_date'],
                'indexes': [models.Index(fields=['backtest_run_id', 'trade_date'], name='tb_trade_ma_backtes_9a6ffa_idx')],
            },
        ),
        migrations.CreateModel(
            name='BacktestOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtest_run_id', models.CharField(db_index=True, help_text='回测运行的唯一标识符', max_length=50)),
                ('position_id_ref', models.BigIntegerField(db_index=True, help_text='关联的持仓ID (tb_positions.position_id)，用于反查')),
                ('stock_code', models.CharField(help_text="股票代码, 如 'sh.600000'", max_length=50)),
                ('stock_name', models.CharField(help_text='股票名称', max_length=50)),
                ('trade_date', models.DateField(help_text='交易发生的日期')),
                ('direction', models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出')], help_text='买卖方向', max_length=10)),
                ('exit_reason', models.CharField(blank=True, choices=[('TAKE_PROFIT', '止盈'), ('STOP_LOSS', '止损')], help_text='止盈/止损方向 (仅卖出时有效)', max_length=20, null=True)),
                ('profit_rate', models.DecimalField(blank=True, decimal_places=4, help_text='该笔交易设置的止盈率', max_digits=10, null=True)),
                ('loss_rate', models.DecimalField(blank=True, decimal_places=4, help_text='该笔交易设置的止损率', max_digits=10, null=True)),
                ('buy_date_m_value', models.DecimalField(blank=True, decimal_places=10, help_text='买入决策所依据的T-1日市场M(t)值', max_digits=18, null=True)),
                ('factor_scores', models.TextField(help_text='买入时各因子得分, 格式: factor1:score1|factor2:score2')),
                ('price', models.DecimalField(decimal_places=2, help_text='成交价格', max_digits=10)),
                ('quantity', models.BigIntegerField(help_text='成交数量')),
                ('amount', models.DecimalField(decimal_places=4, help_text='成交总金额', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
            ],
            options={
                'verbose_name': '回测操作记录',
                'verbose_name_plural': '回测操作记录',
                'db_table': 'tb_trade_manager_backtest_operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['backtest_run_id', 'stock_code'], name='tb_trade_ma_backtes_4b118e_idx'), models.Index(fields=['backtest_run_id', 'position_id_ref'], name='tb_trade_ma_backtes_f4f8b4_idx')],
            },
        ),
    ]
