# Generated by Django 5.2.4 on 2025-08-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_backtestdailylog_backtestoperationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexQuotesCsi300',
            fields=[
                ('trade_date', models.DateField(help_text='交易日期', primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=2, help_text='开盘价', max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, help_text='收盘价', max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, help_text='最高价', max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, help_text='最低价', max_digits=10)),
                ('volume', models.BigIntegerField(help_text='成交量 (股)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='成交额 (元)', max_digits=20)),
                ('amplitude', models.DecimalField(decimal_places=4, help_text='振幅 (%)', max_digits=8)),
                ('pct_change', models.DecimalField(decimal_places=4, help_text='涨跌幅 (%)', max_digits=8)),
                ('change_amount', models.DecimalField(decimal_places=2, help_text='涨跌额', max_digits=10)),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=4, help_text='换手率 (%)', max_digits=8, null=True)),
            ],
            options={
                'verbose_name': '沪深300指数行情',
                'verbose_name_plural': '沪深300指数行情',
                'db_table': 'tb_index_quotes_csi300',
                'ordering': ['-trade_date'],
            },
        ),
    ]
