# Generated by Django 5.2.4 on 2025-08-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_indexquotescsi300'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDistributionBacktestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtest_run_id', models.CharField(db_index=True, help_text='回测运行的唯一标识符', max_length=50)),
                ('plan_date', models.DateField(help_text='预案生成日期 (T-1日)')),
                ('stock_code', models.CharField(help_text='股票代码', max_length=50)),
                ('stock_name', models.CharField(help_text='股票名称', max_length=50)),
                ('m_value_at_plan', models.DecimalField(decimal_places=10, help_text='预案生成日的市场M(t)值', max_digits=18)),
                ('strategy_dna', models.CharField(help_text='策略DNA贡献度, 格式: MT:0.70|BO:0.20|MR:0.05|QD:0.05', max_length=255)),
                ('entry_date', models.DateField(help_text='模拟入场日期 (T日)')),
                ('entry_price', models.DecimalField(decimal_places=2, help_text='模拟入场价格 (T日开盘价)', max_digits=10)),
                ('exit_date', models.DateField(help_text='模拟出场日期')),
                ('exit_price', models.DecimalField(decimal_places=2, help_text='模拟出场价格', max_digits=10)),
                ('exit_reason', models.CharField(choices=[('TAKE_PROFIT', '止盈'), ('STOP_LOSS', '止损'), ('END_OF_PERIOD', '达到最大持有期')], help_text='平仓原因', max_length=20)),
                ('holding_period', models.IntegerField(help_text='持有天数（交易日）')),
                ('preset_take_profit_rate', models.DecimalField(decimal_places=4, help_text='根据策略计算出的预设止盈率', max_digits=10)),
                ('preset_stop_loss_rate', models.DecimalField(decimal_places=4, help_text='根据策略计算出的预设止损率', max_digits=10)),
                ('actual_return_rate', models.DecimalField(decimal_places=4, help_text='该笔交易的实际收益率 ( (exit_price / entry_price) - 1 )', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'M值分布回测日志',
                'verbose_name_plural': 'M值分布回测日志',
                'db_table': 'tb_m_distribution_backtest_log',
                'indexes': [models.Index(fields=['backtest_run_id', 'plan_date'], name='tb_m_distri_backtes_a485b1_idx')],
            },
        ),
    ]
