# Generated by Django 5.2.4 on 2025-08-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_mdistributionbacktestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytradingplan',
            name='strategy_dna',
            field=models.CharField(blank=True, help_text='策略DNA贡献度, 格式: MT:0.70|BO:0.20|MR:0.05|QD:0.05', max_length=255, null=True),
        ),
    ]
