# Generated by Django 5.2.4 on 2025-08-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_dailytradingplan_strategy_dna'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdistributionbacktestlog',
            name='one_stratage_mode',
            field=models.CharField(blank=True, db_index=True, help_text='单策略模式下使用的策略名 (MT, BO, QD, MR), 为空则为M动态策略', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='mdistributionbacktestlog',
            index=models.Index(fields=['backtest_run_id', 'one_stratage_mode'], name='tb_m_distri_backtes_7fe112_idx'),
        ),
    ]
