# Generated by Django 5.2.4 on 2025-09-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_mdistributionbacktestlog_one_stratage_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdistributionbacktestlog',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='买入决策时，个股的选股模型最终得分', max_digits=18, null=True),
        ),
    ]
