# Generated by Django 5.2.4 on 2025-09-10 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_mdistributionbacktestlog_final_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='AI资源的名称，如OpenAI、Claude等', max_length=100, unique=True, verbose_name='资源名称')),
                ('url', models.URLField(help_text='AI服务的API端点URL', max_length=500, verbose_name='资源URL')),
                ('api_key', models.CharField(help_text='访问AI服务的API密钥', max_length=500, verbose_name='API密钥')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此AI资源', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.TextField(blank=True, help_text='AI资源的详细描述', null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': 'AI资源配置',
                'verbose_name_plural': 'AI资源配置',
                'db_table': 'tb_ai_source_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='AI模型的名称，如gpt-3.5-turbo、claude-3等', max_length=100, unique=True, verbose_name='模型名称')),
                ('model_type', models.IntegerField(choices=[(1, '文本模型'), (2, '生图模型')], default=1, help_text='模型类型：1-文本模型，2-生图模型', verbose_name='模型类型')),
                ('model_id', models.CharField(help_text='在AI服务中的具体模型标识符', max_length=200, verbose_name='模型ID')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此AI模型', verbose_name='是否启用')),
                ('max_tokens', models.IntegerField(default=1000, help_text='模型单次请求的最大Token数量', verbose_name='最大Token数')),
                ('temperature', models.FloatField(default=0.7, help_text='控制模型输出的随机性，范围0-2', verbose_name='温度参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.TextField(blank=True, help_text='AI模型的详细描述', null=True, verbose_name='描述')),
                ('source', models.ForeignKey(help_text='关联的AI资源配置', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='common.aisourceconfig', verbose_name='资源名称')),
            ],
            options={
                'verbose_name': 'AI模型配置',
                'verbose_name_plural': 'AI模型配置',
                'db_table': 'tb_ai_model_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
