# Generated by Django 5.2.4 on 2025-09-16 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_aisourceconfig_aimodelconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('fund_code', models.CharField(help_text="基金代码, 格式如 'sh.510050'", max_length=50, primary_key=True, serialize=False)),
                ('fund_name', models.CharField(help_text='基金名称', max_length=50)),
                ('fund_type', models.CharField(choices=[('000', '其他'), ('001', '场内ETF')], default='000', help_text='基金类型。枚举: 000(其他), 001(场内ETF)', max_length=3)),
                ('listing_date', models.DateField(help_text='上市日期')),
                ('status', models.CharField(choices=[('listing', '上市'), ('delisted', '退市'), ('suspended', '停牌')], help_text='基金状态。枚举: listing(上市), delisted(退市), suspended(停牌)', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录更新时间')),
            ],
            options={
                'verbose_name': '基金基础信息',
                'verbose_name_plural': '基金基础信息',
                'db_table': 'tb_fund_info',
            },
        ),
        migrations.CreateModel(
            name='FundDailyQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(help_text='交易日期')),
                ('open', models.DecimalField(decimal_places=2, help_text='不复权开盘价', max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, help_text='不复权最高价', max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, help_text='不复权最低价', max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, help_text='不复权收盘价', max_digits=10)),
                ('volume', models.BigIntegerField(help_text='成交量 (股)')),
                ('turnover', models.DecimalField(decimal_places=2, help_text='成交额 (元)', max_digits=20)),
                ('adjust_factor', models.DecimalField(decimal_places=10, help_text='截至当日的后复权因子', max_digits=20)),
                ('hfq_close', models.DecimalField(decimal_places=10, editable=False, help_text='后复权收盘价，公式: close * adjust_factor', max_digits=20)),
                ('fund_code', models.ForeignKey(db_column='fund_code', help_text='基金代码', on_delete=django.db.models.deletion.CASCADE, to='common.fundinfo')),
            ],
            options={
                'verbose_name': '基金日线行情',
                'verbose_name_plural': '基金日线行情',
                'db_table': 'tb_fund_daily_quotes',
                'indexes': [models.Index(fields=['trade_date'], name='funddailyquotes_tradedate_idx')],
                'unique_together': {('fund_code', 'trade_date')},
            },
        ),
    ]
