# Generated by Django 5.2.4 on 2025-09-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_fundinfo_funddailyquotes'),
    ]

    operations = [
    ]
