# Generated by Django 5.2.4 on 2025-09-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20250916_1440'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyquotes',
            index=models.Index(fields=['stock_code', 'trade_date'], name='dq_stock_date_idx'),
        ),
        migrations.AddIndex(
            model_name='funddailyquotes',
            index=models.Index(fields=['fund_code', 'trade_date'], name='fdq_fund_date_idx'),
        ),
    ]
